sudo: required

services:
  - docker
env:
  matrix:
    - WSREP_EXTRA_OPT=wssrep_method=mysqldump 
    - WSREP_EXTRA_OPT=wssrep_method=rsync
    - WSREP_EXTRA_OPT=wssrep_method=xtrabackup
    - WSREP_EXTRA_OPT=wssrep_method=xtrabackup-v2

script:
  - cd _bugscript && bash -x show_bug_in_docker.sh
