sudo: required

services:
  - docker
env:
  matrix:
    - ENVIRON=10.2.6 WSREP_EXTRA_OPT=wsrep_sst_method=mysqldump
    - ENVIRON=10.2.6 WSREP_EXTRA_OPT=wsrep_sst_method=rsync
    - ENVIRON=10.2.6 WSREP_EXTRA_OPT=wsrep_sst_method=xtrabackup
    - ENVIRON=10.2.6 WSREP_EXTRA_OPT=wsrep_sst_method=xtrabackup-v2
    - ENVIRON=10.1.25 WSREP_EXTRA_OPT=wsrep_sst_method=mysqldump
    - ENVIRON=10.1.25 WSREP_EXTRA_OPT=wsrep_sst_method=rsync
    - ENVIRON=10.1.25 WSREP_EXTRA_OPT=wsrep_sst_method=xtrabackup
    - ENVIRON=10.1.25 WSREP_EXTRA_OPT=wsrep_sst_method=xtrabackup-v2
    - ENVIRON=10.1.25 WSREP_EXTRA_OPT=wsrep_sst_method=mariabackup

script:
  - cd _bugscript && bash -x -v show_bug_in_docker.sh
