sudo: required

services:
  - docker

install:
  - yum install http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm -y
  - yum install xtrabackup-24 -y

env:
  matrix:
    - WSREP_EXTRA_OPT=wssrep_method=mysqldump 
    - WSREP_EXTRA_OPT=wssrep_method=rsync
    - WSREP_EXTRA_OPT=wssrep_method=xtrabackup
    - WSREP_EXTRA_OPT=wssrep_method=xtrabackup-v2

script:
  - [[ ! "$WSREP_EXTRA_OPT" =~ xtrabackup ]] || { yum install http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm -y && yum install xtrabackup-24 -y; }
  - cd _bugscript && bash -x show_bug_in_docker.sh
